# Check out the default config: https://bitbucket.org/Prunt/restrictedcreative/wiki/Default%20config
# Config explanation: https://bitbucket.org/Prunt/restrictedcreative/wiki/Home#markdown-header-config-explanation
#
general:
  saving:
    interval: 6000

creative:
  armor:
    enabled: true
    type: 'leather'
    color: 16711680
  permissions:
    enabled: false
    use-vault: true
    list:
    - 'prefix.creative'
    - '-prefix.survival'
  groups:
    enabled: false
    list:
    - 'creative'
    - '-survival'

limit:
  interact:
    inventories: true
    entities: true
    breeding: true
    slimefun: true
  combat:
    pvp: true
    pve: true
